-- ============================================================
-- Migration 018: Medications Library Seed
-- 260 real medications from Ghanaian pharmacies, seeded as
-- approved entries. ON CONFLICT skips duplicates safely.
-- ============================================================

BEGIN;

INSERT INTO public.medications_library
  (name, generic_name, dosage_form, strength, unit_of_measure,
   category, requires_prescription, source, status)
VALUES
  ('Gebedol Tablets','Paracetamol','Tablet',NULL,'Tablet','Analgesics',false,'seed','approved'),
  ('Ciprolex-TZ Tablets','Ciprofloxacin + Tinidazole','Tablet',NULL,'Tablet','Antibiotics',true,'seed','approved'),
  ('Paracetamol 500 mg Tablets','Paracetamol','Tablet','500mg','Tablet','Analgesics',false,'seed','approved'),
  ('M-Z Tone Tablets',NULL,'Tablet',NULL,'Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Zyfen 120 mg Tablets','Fexofenadine','Tablet','120mg','Tablet','Antihistamines',false,'seed','approved'),
  ('Hycid Capsules','Hyoscine','Capsule',NULL,'Capsule','Antispasmodics',false,'seed','approved'),
  ('Letacam','Diclofenac','Tablet',NULL,'Tablet','Analgesics',false,'seed','approved'),
  ('Losartan 100 mg Tablets','Losartan','Tablet','100mg','Tablet','Antihypertensives',true,'seed','approved'),
  ('Amlova 10 mg Tablets','Amlodipine','Tablet','10mg','Tablet','Antihypertensives',true,'seed','approved'),
  ('Vermox 500 mg Tablets','Mebendazole','Tablet','500mg','Tablet','Anthelmintics',false,'seed','approved'),
  ('Doxy Tablets','Doxycycline','Tablet',NULL,'Tablet','Antibiotics',true,'seed','approved'),
  ('Oxytetra 250 mg Capsules','Oxytetracycline','Capsule','250mg','Capsule','Antibiotics',true,'seed','approved'),
  ('Ronfit Forte Capsules',NULL,'Capsule',NULL,'Capsule','Vitamins & Supplements',false,'seed','approved'),
  ('Nifecard XL 30 mg Tablets','Nifedipine','Tablet','30mg','Tablet','Antihypertensives',true,'seed','approved'),
  ('Zintab 10 mg Tablets','Zinc','Tablet','10mg','Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Sermens Capsules',NULL,'Capsule',NULL,'Capsule','Other',false,'seed','approved'),
  ('Amoksiklav 625 mg Tablets','Amoxicillin + Clavulanate','Tablet','625mg','Tablet','Antibiotics',true,'seed','approved'),
  ('Dexone Tablets','Dexamethasone','Tablet',NULL,'Tablet','Corticosteroids',true,'seed','approved'),
  ('Celecoxib 200 mg','Celecoxib','Tablet','200mg','Tablet','Analgesics',false,'seed','approved'),
  ('Lifetone Capsules',NULL,'Capsule',NULL,'Capsule','Vitamins & Supplements',false,'seed','approved'),
  ('Polyfer Capsules','Iron + Folic Acid','Capsule',NULL,'Capsule','Vitamins & Supplements',false,'seed','approved'),
  ('Amciclox Capsules','Ampicillin + Cloxacillin','Capsule',NULL,'Capsule','Antibiotics',true,'seed','approved'),
  ('Prednisolone 5 mg Tablets','Prednisolone','Tablet','5mg','Tablet','Corticosteroids',true,'seed','approved'),
  ('Citroc Tablets',NULL,'Tablet',NULL,'Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Wormzap Suspension/Tablets','Mebendazole','Tablet',NULL,'Tablet','Anthelmintics',false,'seed','approved'),
  ('Primolut N 5 mg Tablets','Norethisterone','Tablet','5mg','Tablet','Women''s Health',true,'seed','approved'),
  ('Buscopan Tablets','Hyoscine Butylbromide','Tablet',NULL,'Tablet','Antispasmodics',false,'seed','approved'),
  ('Ginovil Tablets',NULL,'Tablet',NULL,'Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Metrolife F Tablets','Metronidazole + Folic Acid','Tablet',NULL,'Tablet','Antibiotics',true,'seed','approved'),
  ('Rhizin Tablets',NULL,'Tablet',NULL,'Tablet','Anthelmintics',false,'seed','approved'),
  ('Loperon (Loperamide) Capsules','Loperamide','Capsule',NULL,'Capsule','Antidiarrheals',false,'seed','approved'),
  ('Novacip (Ciprofloxacin) Tablets','Ciprofloxacin','Tablet',NULL,'Tablet','Antibiotics',true,'seed','approved'),
  ('Zulu-100 mg Tablets','Fluconazole','Tablet','100mg','Tablet','Antifungals',false,'seed','approved'),
  ('Enaphage 500 mg Tablets','Metformin','Tablet','500mg','Tablet','Antidiabetics',true,'seed','approved'),
  ('Enacin (Clindamycin) 300 mg Capsules','Clindamycin','Capsule','300mg','Capsule','Antibiotics',true,'seed','approved'),
  ('Chloramphenicol Capsules','Chloramphenicol','Capsule',NULL,'Capsule','Antibiotics',true,'seed','approved'),
  ('Broncholin Tablets',NULL,'Tablet',NULL,'Tablet','Respiratory',false,'seed','approved'),
  ('Diclodenk 100 mg Tablets','Diclofenac','Tablet','100mg','Tablet','Analgesics',false,'seed','approved'),
  ('Ibuga Capsules','Ibuprofen','Capsule',NULL,'Capsule','Analgesics',false,'seed','approved'),
  ('Coldrilif Capsules',NULL,'Capsule',NULL,'Capsule','Cold & Flu',false,'seed','approved'),
  ('Ronluz 100 Tablets','Fluconazole','Tablet','100mg','Tablet','Antifungals',false,'seed','approved'),
  ('Zincovit Syrup 200 ml','Zinc + Vitamins','Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Auntie Mary Gripe Water',NULL,'Mixture',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Heptolif Syrup',NULL,'Syrup',NULL,'Bottle','Liver Tonics',false,'seed','approved'),
  ('Coldrilif Syrup',NULL,'Syrup',NULL,'Bottle','Cold & Flu',false,'seed','approved'),
  ('Teedar Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Hoffexa Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Babyvite Syrup',NULL,'Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Apetamin Syrup','Cyproheptadine + Vitamins','Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Enafen (Ibuprofen) Syrup','Ibuprofen','Syrup',NULL,'Bottle','Analgesics',false,'seed','approved'),
  ('Salocold Syrup',NULL,'Syrup',NULL,'Bottle','Cold & Flu',false,'seed','approved'),
  ('Victory G Mixture',NULL,'Mixture',NULL,'Bottle','Other',false,'seed','approved'),
  ('Tres Orix Forte Syrup','Cyproheptadine','Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Ayitone Forte Syrup',NULL,'Syrup',NULL,'Bottle','Tonics',false,'seed','approved'),
  ('Polygrow Syrup',NULL,'Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Fluxacin Suspension','Ciprofloxacin','Suspension',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Becoatin Syrup','B-Complex Vitamins','Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Baby Cough Linctus',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Phizin Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Premoxyl (Amoxicillin) Suspension','Amoxicillin','Suspension',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Macacid Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Zetalin Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Samalin Junior Syrup',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Promecine Syrup',NULL,'Syrup',NULL,'Bottle','Other',false,'seed','approved'),
  ('Visco-F Syrup',NULL,'Syrup',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Abicof Adult',NULL,'Syrup',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Amicof Junior',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Flemex Adult',NULL,'Syrup',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Lubes Cough Mixture',NULL,'Mixture',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Grofyn Tonic',NULL,'Mixture',NULL,'Bottle','Tonics',false,'seed','approved'),
  ('Haemoglobin Syrup',NULL,'Syrup',NULL,'Bottle','Vitamins & Supplements',false,'seed','approved'),
  ('Efpae Junior Syrup',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Taabea Herbal Mixture',NULL,'Mixture',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Time Herbal Mixture',NULL,'Mixture',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Adusa Mixture',NULL,'Mixture',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Givers Mixture',NULL,'Mixture',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Amcof Senior',NULL,'Syrup',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Amcof Junior',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('Amcof Baby',NULL,'Syrup',NULL,'Bottle','Paediatrics',false,'seed','approved'),
  ('MMT',NULL,'Mixture',NULL,'Bottle','Tonics',false,'seed','approved'),
  ('Mucotin Adult',NULL,'Syrup',NULL,'Bottle','Respiratory',false,'seed','approved'),
  ('Arfan Suspension',NULL,'Suspension',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Amok Lavi 228','Amoxicillin + Clavulanate','Suspension','228mg/5ml','Bottle','Antibiotics',true,'seed','approved'),
  ('Amok Lavi 457','Amoxicillin + Clavulanate','Suspension','457mg/5ml','Bottle','Antibiotics',true,'seed','approved'),
  ('Cefuroxime Suspension 50 ml','Cefuroxime','Suspension','125mg/5ml','Bottle','Antibiotics',true,'seed','approved'),
  ('Cefuroxime 750 mg Injection','Cefuroxime','Injection','750mg','Vial','Antibiotics',true,'seed','approved'),
  ('Amciclox Suspension','Ampicillin + Cloxacillin','Suspension',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Ciprolex Ear/Eye Drops','Ciprofloxacin','Drops',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Chlo Ear Drops','Chloramphenicol','Drops',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Klaro Eye Drops',NULL,'Drops',NULL,'Bottle','Eye & Ear',true,'seed','approved'),
  ('Gent Drops','Gentamicin','Drops',NULL,'Bottle','Antibiotics',true,'seed','approved'),
  ('Lonart DS','Artemether + Lumefantrine','Tablet',NULL,'Tablet','Antimalarials',false,'seed','approved'),
  ('Lufart DS','Artemether + Lumefantrine','Tablet',NULL,'Tablet','Antimalarials',false,'seed','approved'),
  ('Lonart Suspension','Artemether + Lumefantrine','Suspension',NULL,'Bottle','Antimalarials',false,'seed','approved'),
  ('Lufart Suspension','Artemether + Lumefantrine','Suspension',NULL,'Bottle','Antimalarials',false,'seed','approved'),
  ('Artesunate Injection 30 mg','Artesunate','Injection','30mg','Vial','Antimalarials',true,'seed','approved'),
  ('Gesunate 60 Injection','Artesunate','Injection','60mg','Vial','Antimalarials',true,'seed','approved'),
  ('Ketazol Cream 30 g','Ketoconazole','Cream','2%','Tube','Antifungals',false,'seed','approved'),
  ('Mizolplus Cream','Miconazole','Cream',NULL,'Tube','Antifungals',false,'seed','approved'),
  ('Herbasoul Cream',NULL,'Cream',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Hydrocortisone Cream 15 g','Hydrocortisone','Cream','1%','Tube','Topicals',false,'seed','approved'),
  ('Funbact Cream Original','Clotrimazole + Beclomethasone','Cream',NULL,'Tube','Antifungals',false,'seed','approved'),
  ('Epiderm Cream 15 g',NULL,'Cream',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Epiderm Cream 30 g',NULL,'Cream',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Drez Ointment 10 g',NULL,'Ointment',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Drez Ointment 30 g',NULL,'Ointment',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Joy Ointment',NULL,'Ointment',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Congo Ointment (Small)',NULL,'Ointment',NULL,'Tube','Topicals',false,'seed','approved'),
  ('NBA Balm',NULL,'Balm',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Chilly Gel',NULL,'Gel',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Protector',NULL,'Cream',NULL,'Tube','Topicals',false,'seed','approved'),
  ('Medisoft Repellent',NULL,'Other',NULL,'Bottle','Other',false,'seed','approved'),
  ('Diclodenk Rectal Suppositories','Diclofenac','Suppository',NULL,'Pack','Analgesics',false,'seed','approved'),
  ('Lofnac 100 Suppositories','Diclofenac','Suppository','100mg','Pack','Analgesics',false,'seed','approved'),
  ('Klovinal Pessaries','Clotrimazole + Metronidazole','Pessary',NULL,'Pack','Women''s Health',false,'seed','approved'),
  ('H1 Lady Wash',NULL,'Liquid',NULL,'Bottle','Women''s Health',false,'seed','approved'),
  ('Condom Ebony',NULL,'Other',NULL,'Pack','Women''s Health',false,'seed','approved'),
  ('Wellwoman Original',NULL,'Tablet',NULL,'Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Tothema Ampoules','Iron + Vitamins','Ampoule',NULL,'Ampoule','Vitamins & Supplements',false,'seed','approved'),
  ('Zincovit Tablets','Zinc + Vitamins','Tablet',NULL,'Tablet','Vitamins & Supplements',false,'seed','approved'),
  ('Cotton Wool 200 g',NULL,'Other',NULL,'Roll','Medical Supplies',false,'seed','approved'),
  ('Gauze Bandage 1 inch',NULL,'Other',NULL,'Roll','Medical Supplies',false,'seed','approved'),
  ('Gauze Bandage 3 inch',NULL,'Other',NULL,'Roll','Medical Supplies',false,'seed','approved'),
  ('Fabric Plaster Strips',NULL,'Other',NULL,'Pack','Medical Supplies',false,'seed','approved'),
  ('Syringe 2 cc + Needle',NULL,'Other',NULL,'Piece','Medical Supplies',false,'seed','approved'),
  ('Syringe 10 cc + Needle 21G',NULL,'Other',NULL,'Piece','Medical Supplies',false,'seed','approved'),
  ('Test Kit Cassette',NULL,'Other',NULL,'Piece','Medical Supplies',false,'seed','approved'),
  ('Dragon Spray',NULL,'Spray',NULL,'Bottle','Other',false,'seed','approved'),
  ('Chicho Soap',NULL,'Soap',NULL,'Bar','Other',false,'seed','approved'),
  ('Tetmosol Soap','Monosulfiram','Soap',NULL,'Bar','Other',false,'seed','approved'),
  ('Kamaclox Mouth Wash',NULL,'Liquid',NULL,'Bottle','Other',false,'seed','approved'),
  ('Listerine 250 ml','Antibacterial rinse','Liquid',NULL,'Bottle','Other',false,'seed','approved'),
  ('Bonamol Inhaler',NULL,'Inhaler',NULL,'Inhaler','Respiratory',false,'seed','approved'),
  ('Picool Inhaler',NULL,'Inhaler',NULL,'Inhaler','Respiratory',false,'seed','approved'),
  ('Redsun Jelly',NULL,'Gel',NULL,'Tube','Other',false,'seed','approved'),
  ('Redsun 100 Tablets',NULL,'Tablet',NULL,'Tablet','Other',false,'seed','approved'),
  ('Shal Toux Lozenges',NULL,'Lozenge',NULL,'Pack','Respiratory',false,'seed','approved'),
  ('Romaf Lozenges',NULL,'Lozenge',NULL,'Pack','Respiratory',false,'seed','approved'),
  ('Liver Salt',NULL,'Powder',NULL,'Sachet','Other',false,'seed','approved'),
  ('Amuzu Pee',NULL,'Other',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Amuzu Garlic',NULL,'Other',NULL,'Bottle','Herbal Medicines',false,'seed','approved'),
  ('Mist Potcit',NULL,'Mixture',NULL,'Bottle','Other',false,'seed','approved'),
  ('Mist Fac.',NULL,'Mixture',NULL,'Bottle','Other',false,'seed','approved'),
  ('Paracetamol 500mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amoxicillin 250mg Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ibuprofen Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Celecoxib 200mg Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Losartan 100mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amlova 10mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Nifecard XL 30mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Prednisolone 5mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Loperamide Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Buscopan Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Cefuroxime Suspension',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Cefuroxime Injection',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amoksiklav 625mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ciprofloxacin Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ciprolex-TZ Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Clindamycin Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Oxytetracycline Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Doxycycline Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Vermox Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lonart DS Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lufart DS Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Artesunate Injection',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Hydrocortisone Cream',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ketazol Cream',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Funbact Cream',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Drez Ointment',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Herbasoul Cream',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zincovit Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Apetamin Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Babyvite Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Wellwoman Original',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Gebedol Tablets',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('M-Z Tone Tablets',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zyfen Tablets',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Hycid Capsules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Letacam',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lofnac Suppository',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Klovinal Pessary',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Auntie Mary Gripe Water',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Liver Salt',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amuzu Pee',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amuzu Garlic',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Dragon Spray',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Chicho Soap',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Tothema Ampoules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Klaro Eye Drops',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Sermens Capsules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Sermens Mixture',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Teedar Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Hoffexa Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Salocold Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Taabea Herbal Mixture',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Polygrow Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Fluxacin Suspension',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Epiderm Cream',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Becoatin Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Baby Cough Linctus',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Tetmosol Soap',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Macacid Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zetalin Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Coldrilif Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Caritef Suspension',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Arfan Suspension',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lifetone Capsules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Polyfer Capsules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Shal Toux Lozenges',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ciprolex Ear/Eye Drops',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Mist Potcit',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zymax Suspension',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Samalin Junior Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Primolut N Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Citroc Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Cameldet 125',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Listerine 250ml',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ginovil Tablets',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Rhizin Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Promecine Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Kamaclox Mouth Wash',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Visco-F Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Abicof Adult',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Amicof Junior',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Flemex Adult',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Bonamol Inhaler',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Novacip Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zulu-100 Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Test Kit Cassette',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lubes Cough Mixture',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Grofyn Tonic',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Joy Ointment',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Mist Fac',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ronluz 100 Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Adusa Mixture',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Cefuroxime 750mg Injection',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Celecoxib 200mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ciprofloxacin 500mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Coldrilif Capsules',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Diclofenac Injection 75mg/3ml',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Diclofenac Suppository',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Doxycycline 100mg Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Epiderm Cream 15g',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Epiderm Cream 30g',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Haemoglobin Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Heptolif Syrup',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Hydrocortisone Cream 15g',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ibuprofen 400mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Ketazol Cream 30g',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lonart DS',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Lufart DS',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Oxytetracycline 250mg Capsule',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Primolut N 5mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Prostafit',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Protector',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Redsun 100 Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Redsun Jelly',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Romaf Lozenges',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Vermox 500mg Tablet',NULL,NULL,NULL,NULL,NULL,false,'seed','approved'),
  ('Zincovit Syrup 200ml',NULL,NULL,NULL,NULL,NULL,false,'seed','approved')
ON CONFLICT (lower(name),lower(COALESCE(dosage_form,'')),lower(COALESCE(strength,''))) DO NOTHING;

COMMIT;